### ISSUE TITLE
Dismatched arguments of class UniformSampler

### ISSUE THREAD

**Issue by xiaolangu** [enosair/federated-fdp#1]
File `data.py`, line 81, `sampler = UniformSampler(
            batch_size=batch_size, niter=niter, data_size=len(subset)
        )`

However, File `sampler.py`, the class is initialized by `def __init__(self, data_source, batch_size)`

**Comment by enosair** [comment]
@xiaolangu Thanks for catching this! Indeed that was my legacy code. I've pushed the changes. Do let me know if it works for you now.

**Comment by xiaolangu** [comment]
> @xiaolangu Thanks for catching this! Indeed that was my legacy code. I've pushed the changes. Do let me know if it works for you now.

@enosair  Thanks for fixing this. It works now! And thanks for the great work!
